[[redirects]]
  from = "/property-management.html"
  to = "/products/property-management"
  status = 301
  
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/publications.html"
  to = "/publications"
  status = 301

[[redirects]]
  from = "/products.html"
  to = "/products"
  status = 301

[[redirects]]
  from = "/art-gallery.html"
  to = "/products/art-gallery"
  status = 301
  force=true

[[redirects]]
  from = "/medical-offices.html"
  to = "/products/medical-offices"
  status = 301



[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/article-1.html"
  to = "/publications/from-genai-novice-to-a-pro-a-non-techies-guide-for-enterprise-ai-integration"
  status = 301

[[redirects]]
  from = "/article-2.html"
  to = "/publications/practical-access-control-for-genai-part-i"
  status = 301


[[redirects]]
  from = "/article-3.html"
  to = "/publications/practical-access-control-for-genai-part-ii"
  status = 301

# Optional: Catch-all rule for other .html files (if any)
[[redirects]]
  from = "/*/*.html"
  to = "/:splat"
  status = 301